// Bit-for-bit parity test between NocturNation's C++ port of the PixMob IR
// encoder (include/pixmob_protocol.h) and the upstream Python reference
// (github.com/jamesw343/PixMob_IR).
//
// The first five reference vectors (RED_PUNCHY, BLUE_GROUP22_C16,
// TWO_COLORS_RED_THEN_GREEN, SET_GROUP_ID, SET_GROUP_SEL) were generated by
// running the Python encoder at jamesw343/PixMob_IR commit HEAD (cloned
// 2026-05-06) for the same inputs the C++ test calls below.
//
// The remaining vectors (TwoColors / CycleProfiles / SetColor variants
// landed in Epic 11 B1 on 2026-06-17) come from tools/pixmob_parity_gen.py,
// a faithful Python port of the encoder. Its faithfulness is verified
// inside this test by REF_TWO_COLORS_RED_GREEN_DUP, which exercises the
// Python port against the same inputs as the original jamesw343-derived
// REF_TWO_COLORS_RED_THEN_GREEN; the two MUST match byte-for-byte for any
// of the Epic 11 vectors to be trustworthy.
//
// To regenerate after upstream changes:
//   1. Update tools/pixmob_parity_gen.py with whatever the change is.
//   2. Run `python3 tools/pixmob_parity_gen.py` and paste the output below
//      the existing arrays (or replace the existing ones if they changed).
//   3. Run `pio test -e native -f test_pixmob_parity` and confirm green.
//
// NOTE on buildCycleProfiles: its `profileMask` argument is described by
// our port as an 8-bit mask, but upstream's `CommandSetConfig` interprets
// the same bits as a profile_id_lo / profile_id_hi range (per architecture
// spec §8.2 footnote). The BYTE encoding is identical either way -
// numerical values pass through unchanged - so byte-level parity tests
// work. Fixing the API parameter name to match upstream semantics is
// captured as a B2 prerequisite in Epic 11.

#include <cstdio>
#include <unity.h>
#include "pixmob_protocol.h"

// ---------------------------------------------------------------------------
// Reference vectors (generated by the Python encoder)
// ---------------------------------------------------------------------------

// CommandSingleColorExt(red=0xFF, green=0x00, blue=0x00,
//                      attack=TIME_32_MS, sustain=TIME_96_MS, release=TIME_96_MS)
static const uint16_t REF_SINGLE_RED_PUNCHY[] = {
    1388, 2082, 1388, 1388, 694, 2776, 694, 1388,
    694, 2776, 694, 2082, 1388, 1388, 694, 1388,
    694, 2776, 694, 2082, 1388, 694, 694, 694,
    694, 1388, 1388, 1388, 694, 694, 1388, 2776,
    694
};
static const size_t REF_SINGLE_RED_PUNCHY_LEN = 33;

// CommandSingleColorExt(red=0x00, green=0x00, blue=0xFF,
//                      attack=TIME_192_MS, sustain=TIME_96_MS, release=TIME_480_MS,
//                      chance=CHANCE_16_PCT, group_id=22)
static const uint16_t REF_SINGLE_BLUE_GROUP22_C16[] = {
    1388, 2776, 1388, 694, 694, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 2082,
    1388, 1388, 694, 2776, 1388, 694, 1388, 2082,
    694, 1388, 694, 694, 694, 694, 694, 2776,
    694
};
static const size_t REF_SINGLE_BLUE_GROUP22_C16_LEN = 33;

// CommandTwoColors(red1=0xFF, green1=0x00, blue1=0x00,
//                 red2=0x00, green2=0xFF, blue2=0x00)
static const uint16_t REF_TWO_COLORS_RED_THEN_GREEN[] = {
    694, 1388, 1388, 694, 694, 1388, 694, 1388,
    694, 694, 694, 694, 1388, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694
};
static const size_t REF_TWO_COLORS_RED_THEN_GREEN_LEN = 35;

// CommandSetGroupId(group_sel=0, new_group_id=22)
static const uint16_t REF_SET_GROUP_ID_SLOT0_GID22[] = {
    694, 694, 694, 694, 694, 694, 1388, 1388,
    694, 694, 694, 694, 694, 1388, 694, 2776,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 2082, 694, 2776, 694, 2082, 694, 694,
    694, 694, 694, 694, 694, 2776, 694
};
static const size_t REF_SET_GROUP_ID_SLOT0_GID22_LEN = 39;

// CommandSetGroupSel(group_sel=0)
static const uint16_t REF_SET_GROUP_SEL_SLOT0[] = {
    1388, 2776, 694, 2082, 694, 694, 694, 694,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 2082, 694, 1388, 1388, 1388, 694, 2776,
    694
};
static const size_t REF_SET_GROUP_SEL_SLOT0_LEN = 33;

// ---------------------------------------------------------------------------
// Epic 11 B1 vectors - generated by tools/pixmob_parity_gen.py.
// Do not edit by hand; regenerate via the script.
// ---------------------------------------------------------------------------

// CommandTwoColors(red→green) - duplicate of existing reference for
// self-check. Output MUST match REF_TWO_COLORS_RED_THEN_GREEN bit-for-bit.
// If this fails, tools/pixmob_parity_gen.py has drifted from the upstream
// encoder and all Epic 11 vectors below are suspect.
static const uint16_t REF_TWO_COLORS_RED_GREEN_DUP[] = {
    694, 1388, 1388, 694, 694, 1388, 694, 1388,
    694, 694, 694, 694, 1388, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694
};
static const size_t REF_TWO_COLORS_RED_GREEN_DUP_LEN = 35;

// CommandTwoColors(white kick, blue tail). Common 'snare + cold-wash'
// composite.
static const uint16_t REF_TWO_COLORS_WHITE_BLUE[] = {
    1388, 1388, 1388, 694, 694, 694, 694, 1388,
    694, 694, 694, 694, 694, 694, 1388, 1388,
    694, 2082, 1388, 1388, 694, 2082, 1388, 1388,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 2082, 1388, 1388, 694
};
static const size_t REF_TWO_COLORS_WHITE_BLUE_LEN = 37;

// CommandTwoColors(amber kick, deep-purple tail). Mid-bright kick + wash
// composite covering non-primary colours.
static const uint16_t REF_TWO_COLORS_AMBER_PURPLE[] = {
    1388, 694, 694, 1388, 1388, 694, 694, 1388,
    694, 694, 694, 694, 1388, 1388, 1388, 694,
    694, 1388, 1388, 1388, 694, 1388, 694, 2776,
    694, 1388, 694, 2776, 694, 2776, 1388, 1388,
    694, 694, 694, 1388, 1388, 694, 694
};
static const size_t REF_TWO_COLORS_AMBER_PURPLE_LEN = 39;

// CommandTwoColors(black, red). Pre-flash 'off' before tail. Exercises
// the all-zero head case.
static const uint16_t REF_TWO_COLORS_BLACK_RED[] = {
    694, 1388, 1388, 694, 1388, 694, 694, 1388,
    694, 694, 694, 694, 1388, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694, 2082, 1388, 1388, 694, 1388,
    694, 2776, 694
};
static const size_t REF_TWO_COLORS_BLACK_RED_LEN = 35;

// CommandTwoColors(black, black). Degenerate all-zero case; verifies the
// encoder's leading-zero-skip behaviour with no data bits set.
static const uint16_t REF_TWO_COLORS_ALL_BLACK[] = {
    694, 1388, 1388, 694, 694, 694, 1388, 1388,
    694, 694, 694, 694, 1388, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694
};
static const size_t REF_TWO_COLORS_ALL_BLACK_LEN = 35;

// CommandCycleProfiles(mask=0x01, random=false, ATK T_32, SUS T_96,
// REL T_192). Single profile, sequential, short envelope.
static const uint16_t REF_CYCLE_PROFILES_SINGLE_SEQ[] = {
    694, 694, 1388, 2082, 694, 2082, 694, 694,
    694, 694, 694, 1388, 694, 1388, 1388, 2082,
    1388, 694, 694, 694, 694, 1388, 694, 694,
    694, 2082, 694
};
static const size_t REF_CYCLE_PROFILES_SINGLE_SEQ_LEN = 27;

// CommandCycleProfiles(mask=0x03, random=false, ATK T_480, SUS T_2400,
// REL T_480). Two-profile A↔B drift with long sustain. The shape Epic 11
// uses for drift_wash on PixMobs.
static const uint16_t REF_CYCLE_PROFILES_TWO_SEQ_LONG[] = {
    694, 694, 1388, 2082, 694, 2082, 694, 694,
    694, 694, 694, 694, 694, 694, 694, 1388,
    1388, 694, 694, 1388, 1388, 694, 694, 694,
    694, 694, 694, 694, 694, 694, 694
};
static const size_t REF_CYCLE_PROFILES_TWO_SEQ_LONG_LEN = 31;

// CommandCycleProfiles(mask=0x0F, random=true, ATK T_96, SUS T_480,
// REL T_960). Four-profile random walk with medium envelope. Exercises
// the random bit + a mask spanning both low- and high-byte payload.
static const uint16_t REF_CYCLE_PROFILES_FOUR_RANDOM[] = {
    694, 694, 1388, 2082, 694, 2082, 694, 694,
    694, 694, 694, 1388, 694, 694, 694, 694,
    694, 2082, 694, 2082, 1388, 694, 694, 694,
    694, 2776, 694
};
static const size_t REF_CYCLE_PROFILES_FOUR_RANDOM_LEN = 27;

// CommandCycleProfiles(mask=0xFF, random=false, ATK T_0, SUS T_3840,
// REL T_0). All eight profiles, max-length sustain, no fade. Exercises
// the all-bits-set encoding path.
static const uint16_t REF_CYCLE_PROFILES_ALL_EIGHT[] = {
    694, 1388, 694, 694, 694, 694, 694, 2082,
    694, 694, 694, 694, 694, 1388, 1388, 1388,
    694, 1388, 694, 694, 694, 1388, 1388, 694,
    694, 1388, 694, 694, 694
};
static const size_t REF_CYCLE_PROFILES_ALL_EIGHT_LEN = 29;

// CommandSetColor(profile=5, r=200, g=100, b=50, isBackground=false,
// skipDisplay=true). Standard profile write, amber. The 'load 16 profile
// slots silently at fleet provisioning' use case.
static const uint16_t REF_SET_COLOR_PROFILE_DEFAULT[] = {
    694, 694, 694, 694, 1388, 1388, 694, 694,
    694, 694, 694, 694, 694, 2082, 1388, 2082,
    694, 694, 694, 694, 1388, 1388, 694, 1388,
    694, 1388, 1388, 694, 694, 1388, 694, 1388,
    1388, 694, 694, 2776, 694, 1388, 694, 2776,
    694
};
static const size_t REF_SET_COLOR_PROFILE_DEFAULT_LEN = 41;

// CommandSetColor(r=200, g=0, b=200, isBackground=true, skipDisplay=false).
// The 'set background and display now' case - Epic 11's primary mapping
// for quiet_wash and the LIGHT_WASH static encoding.
static const uint16_t REF_SET_COLOR_BACKGROUND_PURPLE[] = {
    694, 1388, 1388, 2082, 694, 694, 694, 694,
    694, 694, 694, 1388, 694, 2776, 694, 1388,
    694, 694, 1388, 1388, 694, 694, 694, 694,
    1388, 1388, 694, 2082, 1388, 1388, 694, 694,
    694, 2776, 694, 1388, 694, 2776, 694
};
static const size_t REF_SET_COLOR_BACKGROUND_PURPLE_LEN = 39;

// CommandSetColor(r=0, g=0, b=0, isBackground=true, skipDisplay=false).
// The instant-cancel path for LIGHT_WASH_END; writes black as the new
// background and displays immediately.
static const uint16_t REF_SET_COLOR_BACKGROUND_BLACK[] = {
    1388, 694, 1388, 694, 1388, 1388, 694, 694,
    694, 694, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 2776,
    1388, 1388, 694, 694, 694, 2776, 694, 1388,
    694, 2776, 694
};
static const size_t REF_SET_COLOR_BACKGROUND_BLACK_LEN = 35;

// CommandSetColor(profile=2, r=0, g=255, b=128, isBackground=false,
// skipDisplay=false). Profile write that also displays - exercises the
// skipDisplay=false flag on a non-background write.
static const uint16_t REF_SET_COLOR_PROFILE_SHOW_NOW[] = {
    1388, 694, 694, 694, 1388, 2082, 694, 694,
    694, 694, 694, 2082, 1388, 1388, 694, 1388,
    694, 2776, 694, 1388, 694, 1388, 1388, 694,
    694, 2082, 694, 694, 694, 694, 694, 694,
    694, 2776, 694, 1388, 694, 2776, 694
};
static const size_t REF_SET_COLOR_PROFILE_SHOW_NOW_LEN = 39;

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

static void assert_matches(const char* name,
                           const uint16_t* got, size_t gotLen,
                           const uint16_t* ref, size_t refLen) {
    char msg[128];
    snprintf(msg, sizeof(msg), "%s: pulse-count mismatch", name);
    TEST_ASSERT_EQUAL_size_t_MESSAGE(refLen, gotLen, msg);
    for (size_t i = 0; i < refLen; i++) {
        snprintf(msg, sizeof(msg), "%s: pulse[%zu] mismatch", name, i);
        TEST_ASSERT_EQUAL_UINT16_MESSAGE(ref[i], got[i], msg);
    }
}

void setUp(void) {}
void tearDown(void) {}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

static void test_single_red_punchy(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSingleColor(out, 80,
                                        0xFF, 0x00, 0x00,
                                        pixmob::T_32_MS,
                                        pixmob::T_96_MS,
                                        pixmob::T_96_MS);
    assert_matches("SINGLE_RED_PUNCHY", out, n,
                   REF_SINGLE_RED_PUNCHY, REF_SINGLE_RED_PUNCHY_LEN);
}

static void test_single_blue_group22_chance16(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSingleColor(out, 80,
                                        0x00, 0x00, 0xFF,
                                        pixmob::T_192_MS,
                                        pixmob::T_96_MS,
                                        pixmob::T_480_MS,
                                        pixmob::CHANCE_16,
                                        22);
    assert_matches("SINGLE_BLUE_GROUP22_C16", out, n,
                   REF_SINGLE_BLUE_GROUP22_C16,
                   REF_SINGLE_BLUE_GROUP22_C16_LEN);
}

static void test_two_colors_red_then_green(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0xFF, 0x00, 0x00,
                                      0x00, 0xFF, 0x00);
    assert_matches("TWO_COLORS_RED_THEN_GREEN", out, n,
                   REF_TWO_COLORS_RED_THEN_GREEN,
                   REF_TWO_COLORS_RED_THEN_GREEN_LEN);
}

static void test_set_group_id_slot0_gid22(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetGroupId(out, 80,
                                       /*groupSel=*/0,
                                       /*newGroupId=*/22);
    assert_matches("SET_GROUP_ID_SLOT0_GID22", out, n,
                   REF_SET_GROUP_ID_SLOT0_GID22,
                   REF_SET_GROUP_ID_SLOT0_GID22_LEN);
}

static void test_set_group_sel_slot0(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetGroupSel(out, 80, /*groupSel=*/0);
    assert_matches("SET_GROUP_SEL_SLOT0", out, n,
                   REF_SET_GROUP_SEL_SLOT0,
                   REF_SET_GROUP_SEL_SLOT0_LEN);
}

// ---------------------------------------------------------------------------
// Epic 11 B1 tests: TwoColors / CycleProfiles / SetColor
// ---------------------------------------------------------------------------

// Self-check: the Python port's TwoColors output for the existing
// red→green inputs MUST match the original jamesw343-derived reference.
// If this fails, tools/pixmob_parity_gen.py is broken and any other
// Epic 11 vector below is suspect.
static void test_python_port_self_check_against_existing(void) {
    TEST_ASSERT_EQUAL_size_t_MESSAGE(
        REF_TWO_COLORS_RED_THEN_GREEN_LEN,
        REF_TWO_COLORS_RED_GREEN_DUP_LEN,
        "Python port DUP and original have different pulse counts - "
        "tools/pixmob_parity_gen.py has drifted from jamesw343"
    );
    for (size_t i = 0; i < REF_TWO_COLORS_RED_THEN_GREEN_LEN; i++) {
        char msg[128];
        snprintf(msg, sizeof(msg),
                 "Python port DUP differs from original at pulse[%zu]", i);
        TEST_ASSERT_EQUAL_UINT16_MESSAGE(
            REF_TWO_COLORS_RED_THEN_GREEN[i],
            REF_TWO_COLORS_RED_GREEN_DUP[i],
            msg
        );
    }
}

static void test_two_colors_white_blue(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0xFF, 0xFF, 0xFF,
                                      0x00, 0x00, 0xFF);
    assert_matches("TWO_COLORS_WHITE_BLUE", out, n,
                   REF_TWO_COLORS_WHITE_BLUE,
                   REF_TWO_COLORS_WHITE_BLUE_LEN);
}

static void test_two_colors_amber_purple(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0xFF, 0x80, 0x00,
                                      0x40, 0x00, 0x80);
    assert_matches("TWO_COLORS_AMBER_PURPLE", out, n,
                   REF_TWO_COLORS_AMBER_PURPLE,
                   REF_TWO_COLORS_AMBER_PURPLE_LEN);
}

static void test_two_colors_black_red(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0x00, 0x00, 0x00,
                                      0xFF, 0x00, 0x00);
    assert_matches("TWO_COLORS_BLACK_RED", out, n,
                   REF_TWO_COLORS_BLACK_RED,
                   REF_TWO_COLORS_BLACK_RED_LEN);
}

static void test_two_colors_all_black(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0x00, 0x00, 0x00,
                                      0x00, 0x00, 0x00);
    assert_matches("TWO_COLORS_ALL_BLACK", out, n,
                   REF_TWO_COLORS_ALL_BLACK,
                   REF_TWO_COLORS_ALL_BLACK_LEN);
}

static void test_cycle_profiles_single_seq(void) {
    uint16_t out[80];
    size_t n = pixmob::buildCycleProfiles(out, 80,
                                          /*profileMask=*/0x01,
                                          /*random=*/false,
                                          pixmob::T_32_MS,
                                          pixmob::T_96_MS,
                                          pixmob::T_192_MS);
    assert_matches("CYCLE_PROFILES_SINGLE_SEQ", out, n,
                   REF_CYCLE_PROFILES_SINGLE_SEQ,
                   REF_CYCLE_PROFILES_SINGLE_SEQ_LEN);
}

static void test_cycle_profiles_two_seq_long(void) {
    uint16_t out[80];
    size_t n = pixmob::buildCycleProfiles(out, 80,
                                          /*profileMask=*/0x03,
                                          /*random=*/false,
                                          pixmob::T_480_MS,
                                          pixmob::T_2400_MS,
                                          pixmob::T_480_MS);
    assert_matches("CYCLE_PROFILES_TWO_SEQ_LONG", out, n,
                   REF_CYCLE_PROFILES_TWO_SEQ_LONG,
                   REF_CYCLE_PROFILES_TWO_SEQ_LONG_LEN);
}

static void test_cycle_profiles_four_random(void) {
    uint16_t out[80];
    size_t n = pixmob::buildCycleProfiles(out, 80,
                                          /*profileMask=*/0x0F,
                                          /*random=*/true,
                                          pixmob::T_96_MS,
                                          pixmob::T_480_MS,
                                          pixmob::T_960_MS);
    assert_matches("CYCLE_PROFILES_FOUR_RANDOM", out, n,
                   REF_CYCLE_PROFILES_FOUR_RANDOM,
                   REF_CYCLE_PROFILES_FOUR_RANDOM_LEN);
}

static void test_cycle_profiles_all_eight(void) {
    uint16_t out[80];
    size_t n = pixmob::buildCycleProfiles(out, 80,
                                          /*profileMask=*/0xFF,
                                          /*random=*/false,
                                          pixmob::T_0_MS,
                                          pixmob::T_3840_MS,
                                          pixmob::T_0_MS);
    assert_matches("CYCLE_PROFILES_ALL_EIGHT", out, n,
                   REF_CYCLE_PROFILES_ALL_EIGHT,
                   REF_CYCLE_PROFILES_ALL_EIGHT_LEN);
}

static void test_set_color_profile_default(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetColor(out, 80,
                                     /*r=*/200, /*g=*/100, /*b=*/50,
                                     /*profileId=*/5,
                                     /*isBackground=*/false,
                                     /*skipDisplay=*/true);
    assert_matches("SET_COLOR_PROFILE_DEFAULT", out, n,
                   REF_SET_COLOR_PROFILE_DEFAULT,
                   REF_SET_COLOR_PROFILE_DEFAULT_LEN);
}

static void test_set_color_background_purple(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetColor(out, 80,
                                     /*r=*/200, /*g=*/0, /*b=*/200,
                                     /*profileId=*/0,
                                     /*isBackground=*/true,
                                     /*skipDisplay=*/false);
    assert_matches("SET_COLOR_BACKGROUND_PURPLE", out, n,
                   REF_SET_COLOR_BACKGROUND_PURPLE,
                   REF_SET_COLOR_BACKGROUND_PURPLE_LEN);
}

static void test_set_color_background_black(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetColor(out, 80,
                                     /*r=*/0, /*g=*/0, /*b=*/0,
                                     /*profileId=*/0,
                                     /*isBackground=*/true,
                                     /*skipDisplay=*/false);
    assert_matches("SET_COLOR_BACKGROUND_BLACK", out, n,
                   REF_SET_COLOR_BACKGROUND_BLACK,
                   REF_SET_COLOR_BACKGROUND_BLACK_LEN);
}

static void test_set_color_profile_show_now(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetColor(out, 80,
                                     /*r=*/0, /*g=*/255, /*b=*/128,
                                     /*profileId=*/2,
                                     /*isBackground=*/false,
                                     /*skipDisplay=*/false);
    assert_matches("SET_COLOR_PROFILE_SHOW_NOW", out, n,
                   REF_SET_COLOR_PROFILE_SHOW_NOW,
                   REF_SET_COLOR_PROFILE_SHOW_NOW_LEN);
}

int main(int, char**) {
    UNITY_BEGIN();
    // Original (pre-Epic-11) tests.
    RUN_TEST(test_single_red_punchy);
    RUN_TEST(test_single_blue_group22_chance16);
    RUN_TEST(test_two_colors_red_then_green);
    RUN_TEST(test_set_group_id_slot0_gid22);
    RUN_TEST(test_set_group_sel_slot0);
    // Epic 11 B1: Python port self-check + new vectors.
    RUN_TEST(test_python_port_self_check_against_existing);
    RUN_TEST(test_two_colors_white_blue);
    RUN_TEST(test_two_colors_amber_purple);
    RUN_TEST(test_two_colors_black_red);
    RUN_TEST(test_two_colors_all_black);
    RUN_TEST(test_cycle_profiles_single_seq);
    RUN_TEST(test_cycle_profiles_two_seq_long);
    RUN_TEST(test_cycle_profiles_four_random);
    RUN_TEST(test_cycle_profiles_all_eight);
    RUN_TEST(test_set_color_profile_default);
    RUN_TEST(test_set_color_background_purple);
    RUN_TEST(test_set_color_background_black);
    RUN_TEST(test_set_color_profile_show_now);
    return UNITY_END();
}
