// Bit-for-bit parity test between NocturNation's C++ port of the PixMob IR
// encoder (include/pixmob_protocol.h) and the upstream Python reference
// (github.com/jamesw343/PixMob_IR).
//
// The reference vectors below were generated by running the Python encoder
// at jamesw343/PixMob_IR commit HEAD (cloned 2026-05-06) for the same inputs
// the C++ test calls below, then converting the resulting bit lists into
// microsecond run-lengths via (count * PULSE_US) where PULSE_US = 694.
//
// To regenerate (e.g. after upstream changes), see tools/regen_parity_vectors.py
// (TODO: ship that script alongside this test in a future commit).
//
// NOTE: pixmob::buildCycleProfiles is intentionally excluded from this test.
// Its `profileMask` argument is documented as an 8-bit mask, but the upstream
// Python `CommandSetConfig` interprets the same bits as a profile_id_lo /
// profile_id_hi range. Reconciling the divergence is an Epic 2 task.

#include <cstdio>
#include <unity.h>
#include "pixmob_protocol.h"

// ---------------------------------------------------------------------------
// Reference vectors (generated by the Python encoder)
// ---------------------------------------------------------------------------

// CommandSingleColorExt(red=0xFF, green=0x00, blue=0x00,
//                      attack=TIME_32_MS, sustain=TIME_96_MS, release=TIME_96_MS)
static const uint16_t REF_SINGLE_RED_PUNCHY[] = {
    1388, 2082, 1388, 1388, 694, 2776, 694, 1388,
    694, 2776, 694, 2082, 1388, 1388, 694, 1388,
    694, 2776, 694, 2082, 1388, 694, 694, 694,
    694, 1388, 1388, 1388, 694, 694, 1388, 2776,
    694
};
static const size_t REF_SINGLE_RED_PUNCHY_LEN = 33;

// CommandSingleColorExt(red=0x00, green=0x00, blue=0xFF,
//                      attack=TIME_192_MS, sustain=TIME_96_MS, release=TIME_480_MS,
//                      chance=CHANCE_16_PCT, group_id=22)
static const uint16_t REF_SINGLE_BLUE_GROUP22_C16[] = {
    1388, 2776, 1388, 694, 694, 2776, 694, 1388,
    694, 2776, 694, 1388, 694, 2776, 694, 2082,
    1388, 1388, 694, 2776, 1388, 694, 1388, 2082,
    694, 1388, 694, 694, 694, 694, 694, 2776,
    694
};
static const size_t REF_SINGLE_BLUE_GROUP22_C16_LEN = 33;

// CommandTwoColors(red1=0xFF, green1=0x00, blue1=0x00,
//                 red2=0x00, green2=0xFF, blue2=0x00)
static const uint16_t REF_TWO_COLORS_RED_THEN_GREEN[] = {
    694, 1388, 1388, 694, 694, 1388, 694, 1388,
    694, 694, 694, 694, 1388, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 2082,
    1388, 1388, 694, 1388, 694, 2776, 694, 1388,
    694, 2776, 694
};
static const size_t REF_TWO_COLORS_RED_THEN_GREEN_LEN = 35;

// CommandSetGroupId(group_sel=0, new_group_id=22)
static const uint16_t REF_SET_GROUP_ID_SLOT0_GID22[] = {
    694, 694, 694, 694, 694, 694, 1388, 1388,
    694, 694, 694, 694, 694, 1388, 694, 2776,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 2082, 694, 2776, 694, 2082, 694, 694,
    694, 694, 694, 694, 694, 2776, 694
};
static const size_t REF_SET_GROUP_ID_SLOT0_GID22_LEN = 39;

// CommandSetGroupSel(group_sel=0)
static const uint16_t REF_SET_GROUP_SEL_SLOT0[] = {
    1388, 2776, 694, 2082, 694, 694, 694, 694,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 1388, 694, 2776, 694, 1388, 694, 2776,
    694, 2082, 694, 1388, 1388, 1388, 694, 2776,
    694
};
static const size_t REF_SET_GROUP_SEL_SLOT0_LEN = 33;

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

static void assert_matches(const char* name,
                           const uint16_t* got, size_t gotLen,
                           const uint16_t* ref, size_t refLen) {
    char msg[128];
    snprintf(msg, sizeof(msg), "%s: pulse-count mismatch", name);
    TEST_ASSERT_EQUAL_size_t_MESSAGE(refLen, gotLen, msg);
    for (size_t i = 0; i < refLen; i++) {
        snprintf(msg, sizeof(msg), "%s: pulse[%zu] mismatch", name, i);
        TEST_ASSERT_EQUAL_UINT16_MESSAGE(ref[i], got[i], msg);
    }
}

void setUp(void) {}
void tearDown(void) {}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

static void test_single_red_punchy(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSingleColor(out, 80,
                                        0xFF, 0x00, 0x00,
                                        pixmob::T_32_MS,
                                        pixmob::T_96_MS,
                                        pixmob::T_96_MS);
    assert_matches("SINGLE_RED_PUNCHY", out, n,
                   REF_SINGLE_RED_PUNCHY, REF_SINGLE_RED_PUNCHY_LEN);
}

static void test_single_blue_group22_chance16(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSingleColor(out, 80,
                                        0x00, 0x00, 0xFF,
                                        pixmob::T_192_MS,
                                        pixmob::T_96_MS,
                                        pixmob::T_480_MS,
                                        pixmob::CHANCE_16,
                                        22);
    assert_matches("SINGLE_BLUE_GROUP22_C16", out, n,
                   REF_SINGLE_BLUE_GROUP22_C16,
                   REF_SINGLE_BLUE_GROUP22_C16_LEN);
}

static void test_two_colors_red_then_green(void) {
    uint16_t out[80];
    size_t n = pixmob::buildTwoColors(out, 80,
                                      0xFF, 0x00, 0x00,
                                      0x00, 0xFF, 0x00);
    assert_matches("TWO_COLORS_RED_THEN_GREEN", out, n,
                   REF_TWO_COLORS_RED_THEN_GREEN,
                   REF_TWO_COLORS_RED_THEN_GREEN_LEN);
}

static void test_set_group_id_slot0_gid22(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetGroupId(out, 80,
                                       /*groupSel=*/0,
                                       /*newGroupId=*/22);
    assert_matches("SET_GROUP_ID_SLOT0_GID22", out, n,
                   REF_SET_GROUP_ID_SLOT0_GID22,
                   REF_SET_GROUP_ID_SLOT0_GID22_LEN);
}

static void test_set_group_sel_slot0(void) {
    uint16_t out[80];
    size_t n = pixmob::buildSetGroupSel(out, 80, /*groupSel=*/0);
    assert_matches("SET_GROUP_SEL_SLOT0", out, n,
                   REF_SET_GROUP_SEL_SLOT0,
                   REF_SET_GROUP_SEL_SLOT0_LEN);
}

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_single_red_punchy);
    RUN_TEST(test_single_blue_group22_chance16);
    RUN_TEST(test_two_colors_red_then_green);
    RUN_TEST(test_set_group_id_slot0_gid22);
    RUN_TEST(test_set_group_sel_slot0);
    return UNITY_END();
}
