#!/usr/bin/env python3
"""Generate PixMob IR encoder parity-test vectors.

This is a Python port of the same encoder in
``include/pixmob_protocol.h``, used to produce the
microsecond-run-length arrays that ``test/test_pixmob_parity/`` asserts
against. Both the C++ and Python ports trace back to
github.com/jamesw343/PixMob_IR (the canonical reverse-engineered
encoder); the original five vectors in the test file were generated by
running jamesw343's Python encoder on 2026-05-06.

This script keeps that provenance chain alive: regenerating vectors no
longer requires cloning the upstream repo. If we ever want to re-verify
against jamesw343 directly, do this:

    git clone https://github.com/jamesw343/PixMob_IR /tmp/PixMob_IR
    cd /tmp/PixMob_IR
    python3 -c "from src.encoder import ..."   # use upstream API
    diff <upstream output> <this script's output>

Run::

    python3 tools/pixmob_parity_gen.py

Output: C++ array literals for the test file, ready to paste in.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Encoder (mirror of pixmob_protocol.h)
# ---------------------------------------------------------------------------

PULSE_US = 694

ENCODING_MAP = [
    0x21, 0x32, 0x54, 0x65, 0xa9, 0x9a, 0x6d, 0x29,
    0x56, 0x92, 0xa1, 0xb4, 0xb2, 0x84, 0x66, 0x2a,
    0x4c, 0x6a, 0xa6, 0x95, 0x62, 0x51, 0x42, 0x24,
    0x35, 0x46, 0x8a, 0xac, 0x8c, 0x6c, 0x2c, 0x4a,
    0x59, 0x86, 0xa4, 0xa2, 0x91, 0x64, 0x55, 0x44,
    0x22, 0x31, 0xb1, 0x52, 0x85, 0x96, 0xa5, 0x69,
    0x5a, 0x2d, 0x4d, 0x89, 0x45, 0x34, 0x61, 0x25,
    0x36, 0xad, 0x94, 0xaa, 0x8d, 0x49, 0x99, 0x26,
]
assert len(ENCODING_MAP) == 64


def encode_buffer_to_us(buf: list[int]) -> list[int]:
    """Encode a 6 or 9-byte buffer into a microsecond run-length list.

    Faithful port of ``encodeBufferToUs`` in pixmob_protocol.h:
      1. Apply ENCODING_MAP to buf[2..end]; accumulate a checksum.
      2. Write the checksum into buf[1] (after mapping it).
      3. Stream bits LSB-first, skipping leading zeros and trailing zeros.
      4. Run-length encode the bit stream; each run becomes count * PULSE_US.
    """
    buf = list(buf)
    checksum_sum = 0
    for i in range(2, len(buf)):
        buf[i] = ENCODING_MAP[buf[i] & 0x3F]
        checksum_sum += buf[i]
    buf[1] = ENCODING_MAP[(checksum_sum >> 2) & 0x3F]

    bits: list[bool] = []
    started = False
    for b in buf:
        for _ in range(8):
            bit = (b & 1) != 0
            if started or bit:
                bits.append(bit)
                started = True
            b >>= 1
    while bits and not bits[-1]:
        bits.pop()

    if not bits:
        return []

    out: list[int] = []
    i = 0
    while i < len(bits):
        j = i
        while j < len(bits) and bits[j] == bits[i]:
            j += 1
        out.append((j - i) * PULSE_US)
        i = j
    return out


# ---------------------------------------------------------------------------
# Time / Chance enums (mirror pixmob_protocol.h)
# ---------------------------------------------------------------------------

T_0_MS    = 0b000
T_32_MS   = 0b001
T_96_MS   = 0b010
T_192_MS  = 0b011
T_480_MS  = 0b100
T_960_MS  = 0b101
T_2400_MS = 0b110
T_3840_MS = 0b111

CHANCE_100 = 0b000
CHANCE_88  = 0b001
CHANCE_67  = 0b010
CHANCE_50  = 0b011
CHANCE_32  = 0b100
CHANCE_16  = 0b101
CHANCE_10  = 0b110
CHANCE_4   = 0b111


# ---------------------------------------------------------------------------
# Command builders (mirror pixmob_protocol.h)
# ---------------------------------------------------------------------------

def build_single_color(r, g, b, attack, sustain, release,
                       chance=CHANCE_100, restrict_group_id=0):
    buf = [0] * 9
    buf[0] = 0x80
    buf[1] = 0x00
    buf[2] = 0x00                                  # type=0b000, on_start=0
    buf[3] = (g >> 2) & 0x3F
    buf[4] = (r >> 2) & 0x3F
    buf[5] = (b >> 2) & 0x3F
    buf[6] = (attack << 3) | (chance & 0x07)
    buf[7] = (release << 3) | (sustain & 0x07)
    buf[8] = restrict_group_id & 0x1F
    return encode_buffer_to_us(buf)


def build_two_colors(r1, g1, b1, r2, g2, b2):
    buf = [0] * 9
    buf[0] = 0x80
    buf[1] = 0x00
    buf[2] = (0b010 << 1)                          # type=0b010, on_start=0
    buf[3] = (g1 >> 2) & 0x3F
    buf[4] = (r1 >> 2) & 0x3F
    buf[5] = (b1 >> 2) & 0x3F
    buf[6] = (g2 >> 2) & 0x3F
    buf[7] = (r2 >> 2) & 0x3F
    buf[8] = (b2 >> 2) & 0x3F
    return encode_buffer_to_us(buf)


def build_cycle_profiles(profile_mask, random, attack, sustain, release):
    """Cycle through enabled profile slots.

    ``profile_mask`` is the 8-bit value that the firmware port stores at
    buf[3] (low 6 bits) plus buf[4] (top 2 bits). The upstream jamesw343
    interpretation is that this is actually a ``profile_range`` field
    encoded as ``(profile_range_lo, profile_range_hi)`` rather than a
    bitmask; see architecture.md §8.2's footnote. For parity testing the
    byte-level encoding is the same regardless of interpretation, so we
    keep the original parameter name.
    """
    buf = [0] * 6
    buf[0] = 0x80
    buf[1] = 0x00
    buf[2] = (0b001 << 1)                          # type=0b001, on_start=0
    buf[3] = profile_mask & 0x3F
    buf[4] = (
        ((profile_mask >> 6) & 0x03)
        | ((1 if random else 0) << 2)
        | ((attack & 0x07) << 3)
    )
    buf[5] = (sustain & 0x07) | ((release & 0x07) << 3)
    return encode_buffer_to_us(buf)


def build_set_color(r, g, b, profile_id, is_background=False,
                    skip_display=True, restrict_group_id=0):
    buf = [0] * 9
    buf[0] = 0x80
    buf[1] = 0x00
    buf[2] = (0b111 << 1) | 1                      # type=0b111, on_start=1
    buf[3] = (g >> 2) & 0x3F
    buf[4] = (r >> 2) & 0x3F
    buf[5] = (b >> 2) & 0x3F
    buf[6] = (
        (profile_id & 0x0F)
        | ((1 if is_background else 0) << 4)
        | ((1 if skip_display else 0) << 5)
    )
    buf[7] = 0                                     # action_id
    buf[8] = restrict_group_id & 0x1F
    return encode_buffer_to_us(buf)


# ---------------------------------------------------------------------------
# Test-vector definitions
# ---------------------------------------------------------------------------
# Each entry: (slug, description, function-call producing the vector).
# The slug becomes the C identifier; the description is the doc-comment
# above the array literal in the generated output.
#
# Naming convention matches the existing test_main.cpp vectors.

VECTORS = [
    # ---- TwoColors: 5 colour-pair variants ----
    ("TWO_COLORS_RED_GREEN_DUP",
     "CommandTwoColors(red→green) - duplicate of existing reference\n"
     "for self-check. Output must match REF_TWO_COLORS_RED_THEN_GREEN.",
     lambda: build_two_colors(0xFF, 0x00, 0x00, 0x00, 0xFF, 0x00)),

    ("TWO_COLORS_WHITE_BLUE",
     "CommandTwoColors(white kick, blue tail). Common 'snare + cold-wash'\n"
     "composite.",
     lambda: build_two_colors(0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF)),

    ("TWO_COLORS_AMBER_PURPLE",
     "CommandTwoColors(amber kick, deep-purple tail). Mid-bright kick +\n"
     "wash composite covering non-primary colours.",
     lambda: build_two_colors(0xFF, 0x80, 0x00, 0x40, 0x00, 0x80)),

    ("TWO_COLORS_BLACK_RED",
     "CommandTwoColors(black, red). Pre-flash 'off' before tail.\n"
     "Exercises the all-zero head case.",
     lambda: build_two_colors(0x00, 0x00, 0x00, 0xFF, 0x00, 0x00)),

    ("TWO_COLORS_ALL_BLACK",
     "CommandTwoColors(black, black). Degenerate all-zero case;\n"
     "useful to verify the encoder's leading-zero-skip behaviour.",
     lambda: build_two_colors(0x00, 0x00, 0x00, 0x00, 0x00, 0x00)),

    # ---- CycleProfiles: 4 mask/random/ASR combinations ----
    # The 8-bit "mask" semantics here mirror the upstream's profile_range
    # field; bytes are identical either way (see build_cycle_profiles
    # docstring).
    ("CYCLE_PROFILES_SINGLE_SEQ",
     "CommandCycleProfiles(mask=0x01, random=false,\n"
     "attack=T_32_MS, sustain=T_96_MS, release=T_192_MS).\n"
     "Single profile, sequential, short envelope.",
     lambda: build_cycle_profiles(0x01, False, T_32_MS, T_96_MS, T_192_MS)),

    ("CYCLE_PROFILES_TWO_SEQ_LONG",
     "CommandCycleProfiles(mask=0x03, random=false,\n"
     "attack=T_480_MS, sustain=T_2400_MS, release=T_480_MS).\n"
     "Two-profile A↔B drift with long sustain. The shape Epic 11 uses\n"
     "for drift_wash on PixMobs.",
     lambda: build_cycle_profiles(0x03, False, T_480_MS, T_2400_MS, T_480_MS)),

    ("CYCLE_PROFILES_FOUR_RANDOM",
     "CommandCycleProfiles(mask=0x0F, random=true,\n"
     "attack=T_96_MS, sustain=T_480_MS, release=T_960_MS).\n"
     "Four-profile random walk with medium envelope. Exercises the\n"
     "random bit + a mask spanning both low- and high-byte payload.",
     lambda: build_cycle_profiles(0x0F, True, T_96_MS, T_480_MS, T_960_MS)),

    ("CYCLE_PROFILES_ALL_EIGHT",
     "CommandCycleProfiles(mask=0xFF, random=false,\n"
     "attack=T_0_MS, sustain=T_3840_MS, release=T_0_MS).\n"
     "All eight profiles, max-length sustain, no fade. Exercises the\n"
     "all-bits-set encoding path.",
     lambda: build_cycle_profiles(0xFF, False, T_0_MS, T_3840_MS, T_0_MS)),

    # ---- SetColor: 4 cases covering isBackground × skipDisplay ----
    ("SET_COLOR_PROFILE_DEFAULT",
     "CommandSetColor(profile=5, r=200, g=100, b=50,\n"
     "isBackground=false, skipDisplay=true). Standard profile-write,\n"
     "amber. The 'load 16 profile slots silently at fleet provisioning'\n"
     "use case.",
     lambda: build_set_color(200, 100, 50, profile_id=5,
                             is_background=False, skip_display=True)),

    ("SET_COLOR_BACKGROUND_PURPLE",
     "CommandSetColor(r=200, g=0, b=200, isBackground=true,\n"
     "skipDisplay=false). The 'set background and display now' case -\n"
     "Epic 11's primary mapping for quiet_wash and the LIGHT_WASH static\n"
     "encoding.",
     lambda: build_set_color(200, 0, 200, profile_id=0,
                             is_background=True, skip_display=False)),

    ("SET_COLOR_BACKGROUND_BLACK",
     "CommandSetColor(r=0, g=0, b=0, isBackground=true,\n"
     "skipDisplay=false). The instant-cancel path for LIGHT_WASH_END;\n"
     "writes black as the new background and displays immediately.",
     lambda: build_set_color(0, 0, 0, profile_id=0,
                             is_background=True, skip_display=False)),

    ("SET_COLOR_PROFILE_SHOW_NOW",
     "CommandSetColor(profile=2, r=0, g=255, b=128,\n"
     "isBackground=false, skipDisplay=false). Profile write that also\n"
     "displays - exercises the skipDisplay=false flag on a non-background\n"
     "write. Less common in shows but worth covering for completeness.",
     lambda: build_set_color(0, 255, 128, profile_id=2,
                             is_background=False, skip_display=False)),
]


def format_vector_as_c(slug: str, description: str, pulses: list[int]) -> str:
    body_lines = ["// " + line for line in description.splitlines()]
    body_lines.append(f"static const uint16_t REF_{slug}[] = {{")
    chunks = []
    for i in range(0, len(pulses), 8):
        row = pulses[i:i + 8]
        chunks.append("    " + ", ".join(f"{v}" for v in row))
    body_lines.append(",\n".join(chunks))
    body_lines.append("};")
    body_lines.append(
        f"static const size_t REF_{slug}_LEN = {len(pulses)};"
    )
    return "\n".join(body_lines)


def main() -> int:
    print("// ============================================================")
    print("// Generated by tools/pixmob_parity_gen.py - do not edit by hand.")
    print("// Regenerate by running the script and pasting the output below")
    print("// the existing reference vectors in test_main.cpp.")
    print("// ============================================================")
    print()
    for slug, description, fn in VECTORS:
        pulses = fn()
        print(format_vector_as_c(slug, description, pulses))
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
